# Generated by Django 5.2.3 on 2025-07-02 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networkimporterjob',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='networkimporterjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='networkimporterjob',
            index=models.Index(fields=['celery_task_id'], name='api_network_celery__ec0cd3_idx'),
        ),
    ]
