# Generated by Django 5.2.4 on 2025-07-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batfishservicesetting',
            name='network_name',
        ),
        migrations.RemoveField(
            model_name='batfishservicesetting',
            name='snapshot_name',
        ),
    ]
